### ISSUE TITLE
can we write in googlesheet using this?

### ISSUE THREAD

**Issue by umesh25** [jadeallencook/gDoc.js#2]
can add update and delete function work with this js?

**Comment by jadeallencook** [comment]
Not yet, should be in possible in the next update.

**Comment by umesh25** [comment]
when will you release your next update?

**Comment by j2l** [comment]
First of all, congrats for this great piece of code!
I have the same need. And not enough skills to decorticate code (https://codelabs.developers.google.com/codelabs/sheets-api/#0) or guts to use a Chinese side project (gridspree).
Would love to see writing to Google sheets working :)
