### ISSUE TITLE
Reaching more rows in a column

### ISSUE THREAD

**Issue by Gabirell** [jadeallencook/gDoc.js#4]
Wow! great js!
This is not an issue, but a question (sorry I'm a newby and I didn't find where to send you an email)
How do you reach another row? I'm making my curriculum this way using your js so what I've done is to make a title like:
Date, Title, Description, etc
So I'm adding a new date, title and description in the rows below but I'm wondering how to reach those infos besides the first row.
Perhaps something to do with the blocks?

Thanks for any help!

**Comment by jadeallencook** [comment]
`gDoc({`
`public: yourPublicId,`
`sheet: 'sheetName',`
`gDoc: 'ul-element-id',`
`columns: ['Date', Title, 'Description', 'etc'],`
`loop: false, // loops over all`
`html: function() {`
`// format your html here`
`var html = '<li>{{Date}} - {{Title}} - {{Description}} - {{etc}}</li>';`
`return html;`
`}`
`});`
